spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  #static页面静态化配置
  resources:
    add-mappings: true  #启用
    cache-period: 3600  #客户端缓存时间
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/ #静态文件路径
  #rabbitMQ配置
  rabbitmq:
    host: 139.199.66.249
    port: 5672
    username: root   #用户名密码为新添加
    password: root
    virtual-host: /
    listener: #消费者
      simple:
        concurrency: 10  #消费者数量
        max-concurrency: 10
        prefetch: 1  #从队列中每次取几个
        auto-startup: true #默认消费者自动启动
        default-requeue-rejected: true #消费失败数据重置
    template:
      retry: #发送者重试，队列满发送者发不进去
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  datasource:
          name: miaosha
          url: jdbc:mysql://139.199.66.249:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: zysung
          password: 160058
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: stat
          maxActive: 1000
          initialSize: 100
          maxWait: 60000
          minIdle: 200
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
redis:
      host: 139.199.66.249
      port: 6379
      password: xxx
      timeout: 1000
      poolMaxTotal: 1000
      poolMaxIdle: 500
      poolMaxWait: 500
mybatis:
  type-aliases-package: cn.zysung.miaosha.po
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:/mapper/*.xml



